version: '3.8'

services:
  # Backend Laravel (Él mismo gestiona su SQLite en un archivo)
  backend:
    build: ./backend
    container_name: laravel_backend
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
    networks:
      - app_network

  # Frontend React
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    networks:
      - app_network

  # Nginx 
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge