# backend/Dockerfile
FROM php:8.4-cli

# Instalar extensiones de sistema y PHP
RUN apt-get update && apt-get install -y \
    libpng-dev libjpeg-dev libfreetype6-dev zip git unzip \
    && docker-php-ext-install pdo_mysql gd

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY . .

RUN composer install --no-dev --optimize-autoloader --ignore-platform-reqs

# Generar APP_KEY si no existe
RUN php artisan key:generate || true

# Start Laravel development server
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=9000"]